main:
  device: cuda
  use_gpt: false
  dataset: horizon #scannet #horizon # hm3dsem #replica #iphone #horizon #replica #horizon #replica # scannet, replica
  scene_id: rosbag2_2025_09_01-17_28_01 #rosbag2_2025_09_01-17_28_01 #rosbag2_2025_08_07-17_31_57 #rosbag2_2025_06_24-12_11_07_fast_livo # #rosbag2_2025_06_24-12_11_07_fast_livo #rosbag2_2025_07_18-19_16_33 #rosbag2_2025_06_24-12_11_07_fast_livo #rosbag2_2025_04_08-21_29_56 #rosbag2_2025_04_08-21_33_17 #demo_iphone_3 #ic4_loop #room0 #scene0518_00 #office0 # scene0011_00
  dataset_path: /mnt/disk1/hovsg/HMA/data/D-robotics/3f-0901
  # /mnt/disk1/hovsg/HMA/data/
  # /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/ 
  # #/mnt/disk1/hovsg/data/scannet # /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/
  #/mnt/disk2/hovsg/HOV-SG/data/hm3dsem_walks/val
  #/mnt/disk2/hovsg/HOV-SG/data/Replica_RGBD/Replica 
  #/mnt/disk2/hovsg/HOV-SG/data/our_dataset/iphone_scan
  #/mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_naviq
  #/mnt/disk2/hovsg/HOV-SG/data/Replica_RGBD/Replica #/mnt/disk1/hovsg/data/scannet/
  save_path:  /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_oldmap_highres
  # /mnt/disk2/hovsg/HOV-SG/data/scannet/scene_graph
  # /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_lowres
  #/mnt/disk2/hovsg/HOV-SG/data/our_dataset/iphone_scan/scene_graph
  #/mnt/disk2/hovsg/HOV-SG/data/Replica_RGBD/scene_graph 
  #/mnt/disk2/hovsg/HOV-SG/data/scannet/
models:
  clip:
    type: ViT-L/14 # ViT-B-32 # ViT-H-14 #ViT-H-14 # ViT-L/14@336px # ViT-H-14
    checkpoint: checkpoints/open_clip_pytorch_model.bin
    # checkpoint: checkpoints/openc_clip_vit_l_14.bin
    # type:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
    # checkpoint: checkpoints/laion2b_s32b_b79k.bin 
    # checkpoint: checkpoints/ovseg_clip.pth 
    # checkpoints/laion2b_s32b_b79k.bin
  sam:
    checkpoint: checkpoints/sam_vit_h_4b8939.pth
    type: vit_h
    points_per_side: 12
    pred_iou_thresh: 0.88
    points_per_batch: 144
    crop_n_layers: 0
    stability_score_thresh: 0.95
    min_mask_region_area: 100
pipeline:
  voxel_size: 0.05
  skip_frames: 20
  init_overlap_thresh: 0.75
  overlap_thresh_factor: 0.025
  iou_thresh: 0.05
  clip_masked_weight: 0.4418
  clip_bbox_margin: 50 # in pixels
  feature_dbscan_eps: 0.01
  max_mask_distance: 10000 # 6.4239 in meters
  min_pcd_points: 100
  depth_weighting: false
  grid_resolution: 0.05
  merge_type: sequential # hierarchical #sequential #hierarchical #sequential #hierarchical # hierarchical, sequential
  save_intermediate_results: true
  obj_labels: SCANNET200 #FINALLABEL #SCANNET200 # FINALLABEL #SCANNET200 #FINALLABEL #SCANNET20 #COCO_STUFF_CLASSES #IMAGENET21K_LABELS #HM3DSEM_LABELS #COCO_STUFF_CLASSES # HM3DSEM_LABELS
  merge_objects_graph: false
