graph_path: /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_oldmap_lowres/horizon/rosbag2_2025_09_01-17_28_01/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap_ovseg/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap_mergenew/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap_merge/horizon/rosbag2_2025_08_07-17_31_57/graph（cur best）
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap_lowres_merge/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_lowres/horizon/rosbag2_2025_08_07-17_31_57/graph(best)
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap_lowres/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_lowres/horizon/rosbag2_2025_08_07-17_31_57/graph
#/mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_newmap_lowres/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_lowres/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_08_07-17_31_57/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_04_08-21_29_56/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_07_18-19_16_33/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_07_18-19_16_33/graph
# /mnt/disk2/hovsg/HOV-SG/data/scannet/scene_graph/scannet/scene0378_00/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_07_18-19_16_33/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_06_24-12_11_07_fast_livo/graph
# /mnt/disk2/hovsg/HOV-SG/data/scannet/scene_graph/scannet/scene0378_00/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_07_18-19_16_33/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs/horizon/rosbag2_2025_06_24-12_11_07_fast_livo/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_lowres/horizon/rosbag2_2025_04_08-21_29_56/graph
# /mnt/disk2/hovsg/HOV-SG/data/our_dataset/g1_navi/scene_graphs_lowres/horizon/rosbag2_2025_04_08-21_33_17/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/our_dataset/iphone_scan/scene_graph/iphone/demo_iphone_3/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/scene_graphs/hm3dsem/00824-Dd4bFSTQ8gi/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/our_dataset/go2_navi/scene_graph/horizon/ic4_loop/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/Replica_RGBD/scene_graph/replica/room0/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/our_dataset/scene_graph_highres/horizon/kitchen/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/scene_graphs/low_res/hm3dsem/00824-Dd4bFSTQ8gi/graph
# graph_path: /mnt/disk2/hovsg/HOV-SG/data/scannet/scannet/scene0011_00/graph