name: mapdsg
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - numpy
    #- pytorch::faiss-gpu
  - pip
  - pip:
    - matplotlib==3.7.3
    - scipy
    - open3d==0.18.0
    - opencv-python
      #    - git+https://github.com/facebookresearch/segment-anything.git
    - torchmetrics
    - ftfy
    - tqdm
    - open-clip-torch
    - transformers
    - openai==1.3.7
    - plyfile
    - hydra-core #Hydra 是一个由 Facebook 开发的 Python 配置管理框架, 不是Hydar-3D-DSG
    - pyvista
    - scikit-fmm
    - pathos
    - opencv-python-headless==4.8.1.78
